UPDATE workflow_requests
SET current_status = CASE current_status
  WHEN 'UNDER_REGISTRAR_REVIEW' THEN 'UNDER_REGISTRAR_VERIFICATION'
  WHEN 'AWAITING_DEAN_APPROVAL' THEN 'UNDER_DEAN_APPROVAL'
  WHEN 'AWAITING_COLLEGE_ADMIN_REVIEW' THEN 'UNDER_COLLEGE_ADMIN_REVIEW'
  WHEN 'FOR_PROCESSING' THEN 'UNDER_REGISTRAR_PROCESSING'
  WHEN 'DOCUMENT_PREPARING' THEN 'DOCUMENT_GENERATION'
  ELSE current_status
END
WHERE current_status IN (
  'UNDER_REGISTRAR_REVIEW',
  'AWAITING_DEAN_APPROVAL',
  'AWAITING_COLLEGE_ADMIN_REVIEW',
  'FOR_PROCESSING',
  'DOCUMENT_PREPARING'
);

UPDATE workflow_request_actions
SET from_status = CASE from_status
  WHEN 'UNDER_REGISTRAR_REVIEW' THEN 'UNDER_REGISTRAR_VERIFICATION'
  WHEN 'AWAITING_DEAN_APPROVAL' THEN 'UNDER_DEAN_APPROVAL'
  WHEN 'AWAITING_COLLEGE_ADMIN_REVIEW' THEN 'UNDER_COLLEGE_ADMIN_REVIEW'
  WHEN 'FOR_PROCESSING' THEN 'UNDER_REGISTRAR_PROCESSING'
  WHEN 'DOCUMENT_PREPARING' THEN 'DOCUMENT_GENERATION'
  ELSE from_status
END,
to_status = CASE to_status
  WHEN 'UNDER_REGISTRAR_REVIEW' THEN 'UNDER_REGISTRAR_VERIFICATION'
  WHEN 'AWAITING_DEAN_APPROVAL' THEN 'UNDER_DEAN_APPROVAL'
  WHEN 'AWAITING_COLLEGE_ADMIN_REVIEW' THEN 'UNDER_COLLEGE_ADMIN_REVIEW'
  WHEN 'FOR_PROCESSING' THEN 'UNDER_REGISTRAR_PROCESSING'
  WHEN 'DOCUMENT_PREPARING' THEN 'DOCUMENT_GENERATION'
  ELSE to_status
END
WHERE from_status IN (
  'UNDER_REGISTRAR_REVIEW',
  'AWAITING_DEAN_APPROVAL',
  'AWAITING_COLLEGE_ADMIN_REVIEW',
  'FOR_PROCESSING',
  'DOCUMENT_PREPARING'
)
OR to_status IN (
  'UNDER_REGISTRAR_REVIEW',
  'AWAITING_DEAN_APPROVAL',
  'AWAITING_COLLEGE_ADMIN_REVIEW',
  'FOR_PROCESSING',
  'DOCUMENT_PREPARING'
);

UPDATE workflow_generated_documents
SET source_status = CASE source_status
  WHEN 'UNDER_REGISTRAR_REVIEW' THEN 'UNDER_REGISTRAR_VERIFICATION'
  WHEN 'AWAITING_DEAN_APPROVAL' THEN 'UNDER_DEAN_APPROVAL'
  WHEN 'AWAITING_COLLEGE_ADMIN_REVIEW' THEN 'UNDER_COLLEGE_ADMIN_REVIEW'
  WHEN 'FOR_PROCESSING' THEN 'UNDER_REGISTRAR_PROCESSING'
  WHEN 'DOCUMENT_PREPARING' THEN 'DOCUMENT_GENERATION'
  ELSE source_status
END
WHERE source_status IN (
  'UNDER_REGISTRAR_REVIEW',
  'AWAITING_DEAN_APPROVAL',
  'AWAITING_COLLEGE_ADMIN_REVIEW',
  'FOR_PROCESSING',
  'DOCUMENT_PREPARING'
);
